# services:
#   app:
#     build: .
#     container_name: elysia_app
#     restart: always
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env.prod
#     environment:
#       NODE_ENV: production
#     command: sh -c "bunx prisma migrate deploy && ./server"
services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-elysia_auth}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-elysia_auth}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: elysia_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: sh -c "bunx prisma migrate deploy && ./server"

volumes:
  postgres_data:
